force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <description>Information about a customer order</description>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Event__e/fields/Has_Shipped__c.field-meta.xml
<CustomField>
    <defaultValue>false</defaultValue>
    <fullName>Has_Shipped__c</fullName>
    <label>Has Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Event__e/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderEventTriggerTest.cls
@isTest
public class OrderEventTriggerTest {
    @isTest
    static void testTrigger() {
        Order_Event__e evt = new Order_Event__e(
            Order_Number__c = '105',
            Has_Shipped__c = true
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(evt);
        Test.stopTest();

        System.assertEquals(true, sr.isSuccess());

        List<Task> tasks = [SELECT Id, Subject FROM Task];
        System.assertEquals(1, tasks.size());
        System.assert(tasks[0].Subject.contains('105'));
    }
}